--- #YAML:1.0
name:               CSS-DOM
version:            0.14
abstract:           Document Object Model for Cascading Style Sheets
author:
    - Father Chrysostomos <sprout & cpan . org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:          1.01
    Clone:         0.09
    constant:      1.03
    Encode:        2.1
    Exporter:      5.57
    overload:      0
    re:            0
    Scalar::Util:  1.09
    strict:        0
    Test::More:    0
    warnings:      0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
